// =====================================================
// PRESENTTRACK — REPORTS PAGE
// =====================================================

document.addEventListener("DOMContentLoaded", () => {

    console.log("Reports page loaded successfully!");


    // =================================================
    // ELEMENTS
    // =================================================

    const reportType =
        document.getElementById("report-type");

    const reportPeriod =
        document.getElementById("report-period");

    const reportFormat =
        document.getElementById("report-format");

    const generateButton =
        document.querySelector(".generate-btn");

    const headerGenerateButton =
        document.querySelector(
            ".page-header .btn-primary"
        );

    const reportCount =
        document.querySelector(".report-count");

    const reportRows =
        Array.from(
            document.querySelectorAll("tbody tr")
        );


    // =================================================
    // GENERATE REPORT
    // =================================================

    function generateReport() {

        const type =
            reportType.value;

        const period =
            reportPeriod.value;

        const format =
            reportFormat.value;


        alert(
            `Report Generated!\n\n` +
            `Type: ${type}\n` +
            `Period: ${period}\n` +
            `Format: ${format}\n\n` +
            `The actual file generation will be connected later.`
        );

    }


    generateButton.addEventListener(
        "click",
        generateReport
    );


    // =================================================
    // HEADER GENERATE BUTTON
    // =================================================

    headerGenerateButton.addEventListener(
        "click",
        () => {

            document.querySelector(
                ".report-form"
            ).scrollIntoView({
                behavior: "smooth"
            });

        }
    );


    // =================================================
    // VIEW REPORT
    // =================================================

    const viewButtons =
        document.querySelectorAll(
            ".table-wrapper .action-btn"
        );


    viewButtons.forEach(button => {

        button.addEventListener(
            "click",
            () => {

                const row =
                    button.closest("tr");


                const reportName =
                    row.cells[0]
                        .textContent
                        .trim();

                const type =
                    row.cells[1]
                        .textContent
                        .trim();

                const period =
                    row.cells[2]
                        .textContent
                        .trim();

                const generatedBy =
                    row.cells[3]
                        .textContent
                        .trim();

                const date =
                    row.cells[4]
                        .textContent
                        .trim();

                const status =
                    row.cells[5]
                        .textContent
                        .trim();


                alert(
                    `Report Details\n\n` +
                    `Report: ${reportName}\n` +
                    `Type: ${type}\n` +
                    `Period: ${period}\n` +
                    `Generated By: ${generatedBy}\n` +
                    `Date: ${date}\n` +
                    `Status: ${status}`
                );

            }
        );

    });


    // =================================================
    // QUICK REPORTS
    // =================================================

    const quickReportButtons =
        document.querySelectorAll(
            ".quick-report-card .action-btn"
        );


    quickReportButtons.forEach(button => {

        button.addEventListener(
            "click",
            () => {

                const card =
                    button.closest(
                        ".quick-report-card"
                    );


                const title =
                    card.querySelector("h3")
                        .textContent
                        .trim();


                alert(
                    `${title}\n\n` +
                    `Your quick report will be generated here once the report system is connected.`
                );

            }
        );

    });


    // =================================================
    // REPORT COUNT
    // =================================================

    function updateReportCount() {

        const visibleReports =
            reportRows.filter(
                row =>
                    row.style.display !== "none"
            ).length;


        // Keep the original total for now.
        // Backend will provide the real number later.

        reportCount.textContent =
            `${reportRows.length} Recent Reports`;

    }


    // =================================================
    // INITIALIZE
    // =================================================

    updateReportCount();

});